# Generated by Django 3.0.5 on 2020-04-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LInk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Nombre Clave')),
                ('name', models.CharField(max_length=100, verbose_name='Red social')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enlace')),
                ('created', models.TimeField(auto_now_add='True', verbose_name='Fecha de Creación')),
                ('updated', models.TimeField(auto_now='True', verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['name'],
            },
        ),
    ]
